### ISSUE TITLE
Update for AAP 2.5

### ISSUE THREAD

**Issue by laurobmb** [redhat-cop/infra.controller_configuration#3]
Is the collection ready to use with AAP 2.5? I'm talking about the filetree role, where there is already a very well-established structure. I see many urls with api/v2/ and today in AAP 2.5 it would be api/controller/v2

**Comment by djdanielsson** [comment]
We have done this https://github.com/redhat-cop/infra.aap_configuration this is a new cloned repo in case the old collection needs bug fixes

**Comment by djdanielsson** [comment]
As for filetree it now lives https://github.com/redhat-cop/aap_configuration_extended
